[package]
name                   = "oxc_allocator"
version                = "0.10.0"
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
categories.workspace   = true

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
bumpalo = { workspace = true, features = ["collections"] }
serde   = { workspace = true }

layout_inspect = { workspace = true, features = ["unique_names"], optional = true }

[dev-dependencies]
serde_json = { workspace = true }

[features]
default = []
raw     = ["dep:layout_inspect"]
